version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
           name: "Build docker image and push to docker hub"
           command: |
              cp Dockerfile.production Dockerfile
              docker build -t wwarodom/example-nodejs-circle:latest .
              docker build -t wwarodom/example-nodejs-circle:${CIRCLE_SHA1} .
              docker push wwarodom/example-nodejs-circle:latest
              docker push wwarodom/example-nodejs-circle:${CIRCLE_SHA1}

      - run: echo Done
